#
# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

known_errors {
  # Entries for known errors due to reference driver bugs. See
  # regression.test for details.
  mode: ALLOW_ERROR_OR_WRONG_ANSWER
  label: "bug_in_reference_impl"
}

known_errors {
  mode: ALLOW_ERROR
  label: "hll_count_test:safe_hll_count_extract_invalid_sketch"
}
