#
# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Known errors file for zetasql compliance framework when using all rewrites.
# Add labels and queries
# here to exclude them from compliance tests.

known_errors {
  mode: ALLOW_ERROR
  reason: "ERROR: generic::internal: ZETASQL_RET_CHECK failure (zetasql/analyzer/rewriters/insert_dml_values_rewriter.cc:61) column->HasDefaultExpression() No default expression exists for the column specified with DEFAULT keyword in insert dml"
  label: "dml_value_table_test:int64_insert_default"
  label: "dml_value_table_test:proto_insert_default"
  label: "dml_value_table_test:struct_insert_default"
}
known_errors {
  mode: ALLOW_ERROR_OR_WRONG_ANSWER
  reason: "Wrong bounds"
  label: "anonymization_test:anonymization_anon_count_double_explicit_bounds_multi_user_with_report_json"
  label: "anonymization_test:anonymization_anon_count_double_explicit_bounds_multi_user_with_report_json_zero_rows"
  label: "anonymization_test:anonymization_anon_count_double_explicit_bounds_multi_user_with_report_proto"
  label: "anonymization_test:anonymization_anon_count_double_explicit_bounds_multi_user_with_report_proto_zero_rows"
  label: "anonymization_test:anonymization_anon_count_star_explicit_bounds_multi_user_with_report_json"
  label: "anonymization_test:anonymization_anon_count_star_explicit_bounds_multi_user_with_report_proto"
  label: "anonymization_test:anonymization_anon_sum_double_explicit_bounds_multi_user_with_report_json"
  label: "anonymization_test:anonymization_anon_sum_double_explicit_bounds_multi_user_with_report_json_zero_rows"
  label: "anonymization_test:anonymization_anon_sum_double_explicit_bounds_multi_user_with_report_proto"
  label: "anonymization_test:anonymization_anon_sum_double_explicit_bounds_multi_user_with_report_proto_zero_rows"
  label: "anonymization_test:anonymization_basic_anon_count_int64_implicit_bounds_multi_user_with_report_json"
  label: "anonymization_test:anonymization_basic_anon_count_int64_implicit_bounds_multi_user_with_report_proto"
  label: "anonymization_test:anonymization_basic_anon_sum_int64_implicit_bounds_multi_user_with_report_json"
  label: "anonymization_test:anonymization_basic_anon_sum_int64_implicit_bounds_multi_user_with_report_proto"
  label: "anonymization_test:anonymization_count_unique_users_with_report_json_with_thresholding"
  label: "anonymization_test:anonymization_count_unique_users_with_report_json_without_thresholding"
  label: "anonymization_test:anonymization_count_unique_users_with_report_proto_with_thresholding"
  label: "anonymization_test:anonymization_count_unique_users_with_report_proto_without_thresholding"
}

known_errors {
  mode: ALLOW_ERROR
  reason: "INVALID_ARGUMENT: The argument to ARRAY_AGG must not be an array type but was ARRAY<DOUBLE>"
  label: "anonymization_test:anonymization_anon_quantiles_double_explicit_bounds_multi_user_with_report_json"
  label: "anonymization_test:anonymization_anon_quantiles_double_explicit_bounds_multi_user_with_report_json_zero_rows"
  label: "anonymization_test:anonymization_anon_quantiles_double_explicit_bounds_multi_user_with_report_proto"
  label: "anonymization_test:anonymization_anon_quantiles_double_explicit_bounds_multi_user_with_report_proto_zero_rows"
  label: "anonymization_test:anonymization_anon_quantiles_int64_explicit_bounds_multi_user_with_report_json"
  label: "anonymization_test:anonymization_anon_quantiles_int64_explicit_bounds_multi_user_with_report_json_zero_rows"
  label: "anonymization_test:anonymization_anon_quantiles_int64_explicit_bounds_multi_user_with_report_proto"
  label: "anonymization_test:anonymization_anon_quantiles_int64_explicit_bounds_multi_user_with_report_proto_zero_rows"
  label: "anonymization_test:anonymization_basic_anon_percentile_cont_explicit_bounds"
  label: "anonymization_test:anonymization_basic_anon_percentile_cont_explicit_bounds_with_delta"
  label: "anonymization_test:anonymization_basic_anon_percentile_cont_implicit_bounds"
  label: "anonymization_test:anonymization_basic_anon_percentile_cont_implicit_bounds_with_delta"
  label: "anonymization_test:anonymization_basic_anon_percentile_cont_implicit_bounds_with_params"
  label: "anonymization_test:anonymization_basic_anon_percentile_cont_implicit_bounds_with_params_with_delta"
  label: "anonymization_test:anonymization_basic_anon_percentile_cont_with_null_epsilon"
  label: "anonymization_test:anonymization_basic_anon_percentile_cont_with_null_epsilon_with_delta"
  label: "anonymization_test:anonymization_basic_anon_quantiles_explicit_bounds"
  label: "anonymization_test:anonymization_basic_anon_quantiles_explicit_bounds_result_length"
  label: "anonymization_test:anonymization_basic_anon_quantiles_with_null_delta"
  label: "anonymization_test:anonymization_basic_anon_quantiles_with_null_epsilon"
  label: "anonymization_test:anonymization_basic_anon_stddev_pop_explicit_bounds"
  label: "anonymization_test:anonymization_basic_anon_stddev_pop_explicit_bounds_all_nulls"
  label: "anonymization_test:anonymization_basic_anon_stddev_pop_explicit_bounds_all_nulls_with_delta"
  label: "anonymization_test:anonymization_basic_anon_stddev_pop_explicit_bounds_with_delta"
  label: "anonymization_test:anonymization_basic_anon_stddev_pop_implicit_bounds"
  label: "anonymization_test:anonymization_basic_anon_stddev_pop_implicit_bounds_with_delta"
  label: "anonymization_test:anonymization_basic_anon_var_pop_explicit_bounds"
  label: "anonymization_test:anonymization_basic_anon_var_pop_explicit_bounds_all_nulls"
  label: "anonymization_test:anonymization_basic_anon_var_pop_explicit_bounds_all_nulls_with_delta"
  label: "anonymization_test:anonymization_basic_anon_var_pop_explicit_bounds_with_delta"
  label: "anonymization_test:anonymization_basic_anon_var_pop_implicit_bounds"
  label: "anonymization_test:anonymization_basic_anon_var_pop_implicit_bounds_with_delta"
  label: "anonymization_test:anonymization_public_groups_with_group_by"
  label: "anonymization_test:anonymization_verify_non_randomness_of_anon_percentile_cont_implicit_bounds"
  label: "anonymization_test:anonymization_verify_non_randomness_of_anon_percentile_cont_implicit_bounds_2"
  label: "anonymization_test:anonymization_verify_non_randomness_of_anon_percentile_cont_implicit_bounds_2_with_delta"
  label: "anonymization_test:anonymization_verify_non_randomness_of_anon_percentile_cont_implicit_bounds_with_delta"
  label: "anonymization_test:anonymization_verify_non_randomness_of_anon_quantiles_explicit_bounds"
  label: "anonymization_test:anonymization_verify_non_randomness_of_anon_quantiles_explicit_bounds_2"
  label: "anonymization_test:anonymization_verify_non_randomness_of_anon_var_pop_implicit_bounds"
  label: "anonymization_test:anonymization_verify_non_randomness_of_anon_var_pop_implicit_bounds_with_delta"
  label: "anonymization_test:anonymization_verify_randomness_of_anon_var_pop_implicit_bounds"
  label: "anonymization_test:anonymization_verify_randomness_of_anon_var_pop_implicit_bounds_with_delta"
}

known_errors {
  mode: ALLOW_ERROR
  reason: "Unsupported function in SELECT WITH ANONYMIZATION select list: SUM"
  label: "anonymization_test:anonymization_min_privacy_units_per_group_is_2"
  label: "anonymization_test:anonymization_min_privacy_units_per_group_is_3"
  label: "anonymization_test:anonymization_min_privacy_units_per_group_is_4"
  label: "anonymization_test:anonymization_min_privacy_units_per_group_is_one"
  label: "anonymization_test:anonymization_min_privacy_units_per_group_and_explicit_laplace_thresholding"
  label: "anonymization_test:anonymization_min_privacy_units_per_group_works_with_json_report"
  label: "anonymization_test:anonymization_min_privacy_units_per_group_works_with_proto_report"
}

known_errors {
  mode: ALLOW_ERROR
  reason: "invalid_argument: Epsilon must be finite and positive, but is -0.333333."
  label: "anonymization_errors_test:epsilon_is_negative"
}

known_errors {
  mode: ALLOW_UNIMPLEMENTED
  reason: "Use of aggregate function ANY_VALUE as PIVOT expression is not supported"
  label: "pivot_test:having_in_aggregate_fn_call"
  label: "pivot_test:having_min_with_reference"
  label: "pivot_test:pivot_any_value_array_groupby"
  label: "pivot_test:pivot_any_value_array_no_groupby"
  label: "pivot_test:pivot_any_value_empty_input"
  label: "pivot_test:pivot_any_value_empty_input_array"
  label: "pivot_test:pivot_any_value_groupby_z"
  label: "pivot_test:pivot_any_value_multiple"
  label: "pivot_test:pivot_any_value_no_groupby"
  label: "pivot_test:pivot_array_agg"
  label: "pivot_test:pivot_st_nearest_neighbors"
}
known_errors {
  mode: ALLOW_ERROR_OR_WRONG_ANSWER
  reason: "Example: Bounds are different floating point values"
  label: "differential_privacy_test:differential_privacy_basic_count_int64_implicit_bounds_multi_user_with_report_json"
  label: "differential_privacy_test:differential_privacy_basic_count_int64_implicit_bounds_multi_user_with_report_proto"
  label: "differential_privacy_test:differential_privacy_basic_sum_int64_implicit_bounds_multi_user_with_report_json"
  label: "differential_privacy_test:differential_privacy_basic_sum_int64_implicit_bounds_multi_user_with_report_proto"
  label: "differential_privacy_test:differential_privacy_count_double_explicit_bounds_multi_user_with_report_json"
  label: "differential_privacy_test:differential_privacy_count_double_explicit_bounds_multi_user_with_report_json_zero_rows"
  label: "differential_privacy_test:differential_privacy_count_double_explicit_bounds_multi_user_with_report_proto"
  label: "differential_privacy_test:differential_privacy_count_double_explicit_bounds_multi_user_with_report_proto_zero_rows"
  label: "differential_privacy_test:differential_privacy_count_star_explicit_bounds_multi_user_with_report_json"
  label: "differential_privacy_test:differential_privacy_count_star_explicit_bounds_multi_user_with_report_proto"
  label: "differential_privacy_test:differential_privacy_count_unique_users_with_report_json_thresholding"
  label: "differential_privacy_test:differential_privacy_sum_double_explicit_bounds_multi_user_with_report_json"
  label: "differential_privacy_test:differential_privacy_sum_double_explicit_bounds_multi_user_with_report_json_zero_rows"
  label: "differential_privacy_test:differential_privacy_sum_double_explicit_bounds_multi_user_with_report_proto"
  label: "differential_privacy_test:differential_privacy_sum_double_explicit_bounds_multi_user_with_report_proto_zero_rows"
}
known_errors {
  mode: ALLOW_ERROR
  reason: "Example: Unsupported function in SELECT WITH DIFFERENTIAL_PRIVACY select list: SUM"
  label: "differential_privacy_test:differential_privacy_approx_quantiles_double_explicit_bounds_multi_user_with_report_json"
  label: "differential_privacy_test:differential_privacy_approx_quantiles_double_explicit_bounds_multi_user_with_report_json_zero_rows"
  label: "differential_privacy_test:differential_privacy_approx_quantiles_double_explicit_bounds_multi_user_with_report_proto"
  label: "differential_privacy_test:differential_privacy_approx_quantiles_double_explicit_bounds_multi_user_with_report_proto_zero_rows"
  label: "differential_privacy_test:differential_privacy_approx_quantiles_int64_explicit_bounds_multi_user_with_report_json"
  label: "differential_privacy_test:differential_privacy_approx_quantiles_int64_explicit_bounds_multi_user_with_report_json_zero_rows"
  label: "differential_privacy_test:differential_privacy_approx_quantiles_int64_explicit_bounds_multi_user_with_report_proto"
  label: "differential_privacy_test:differential_privacy_approx_quantiles_int64_explicit_bounds_multi_user_with_report_proto_zero_rows"
  label: "differential_privacy_test:differential_privacy_basic_approx_quantiles_explicit_bounds"
  label: "differential_privacy_test:differential_privacy_basic_approx_quantiles_explicit_bounds_result_length"
  label: "differential_privacy_test:differential_privacy_basic_epsilon_not_set"
  label: "differential_privacy_test:differential_privacy_basic_percentile_cont_explicit_bounds"
  label: "differential_privacy_test:differential_privacy_basic_percentile_cont_implicit_bounds"
  label: "differential_privacy_test:differential_privacy_basic_percentile_cont_implicit_bounds_with_params"
  label: "differential_privacy_test:differential_privacy_basic_stddev_pop_explicit_bounds"
  label: "differential_privacy_test:differential_privacy_basic_stddev_pop_explicit_bounds_all_nulls"
  label: "differential_privacy_test:differential_privacy_basic_stddev_pop_implicit_bounds"
  label: "differential_privacy_test:differential_privacy_basic_var_pop_explicit_bounds"
  label: "differential_privacy_test:differential_privacy_basic_var_pop_explicit_bounds_all_nulls"
  label: "differential_privacy_test:differential_privacy_basic_var_pop_implicit_bounds"
  label: "differential_privacy_test:differential_privacy_min_privacy_units_per_group_and_explicit_laplace_thresholding"
  label: "differential_privacy_test:differential_privacy_min_privacy_units_per_group_is_2"
  label: "differential_privacy_test:differential_privacy_min_privacy_units_per_group_is_3"
  label: "differential_privacy_test:differential_privacy_min_privacy_units_per_group_is_4"
  label: "differential_privacy_test:differential_privacy_min_privacy_units_per_group_is_one"
  label: "differential_privacy_test:differential_privacy_min_privacy_units_per_group_works_with_json_report"
  label: "differential_privacy_test:differential_privacy_min_privacy_units_per_group_works_with_proto_report"
  label: "differential_privacy_test:differential_privacy_public_groups_with_group_by"
  label: "differential_privacy_test:differential_privacy_verify_non_randomness_of_approx_quantiles_explicit_bounds"
  label: "differential_privacy_test:differential_privacy_verify_non_randomness_of_approx_quantiles_explicit_bounds_2"
  label: "differential_privacy_test:differential_privacy_verify_non_randomness_of_percentile_cont_implicit_bounds"
  label: "differential_privacy_test:differential_privacy_verify_non_randomness_of_percentile_cont_implicit_bounds_2"
  label: "differential_privacy_test:differential_privacy_verify_non_randomness_of_var_pop_implicit_bounds"
  label: "differential_privacy_test:differential_privacy_verify_randomness_of_var_pop_implicit_bounds"
}
known_errors {
  mode: ALLOW_ERROR
  reason: "Example: DIFFERENTIAL_PRIVACY query must query data with a specified privacy unit column"
  label: "differential_privacy_unit_column_test:differential_privacy_approx_quantiles_double_explicit_bounds_multi_user_with_report_json"
  label: "differential_privacy_unit_column_test:differential_privacy_approx_quantiles_double_explicit_bounds_multi_user_with_report_json_zero_rows"
  label: "differential_privacy_unit_column_test:differential_privacy_approx_quantiles_double_explicit_bounds_multi_user_with_report_proto"
  label: "differential_privacy_unit_column_test:differential_privacy_approx_quantiles_double_explicit_bounds_multi_user_with_report_proto_zero_rows"
  label: "differential_privacy_unit_column_test:differential_privacy_approx_quantiles_int64_explicit_bounds_multi_user_with_report_json"
  label: "differential_privacy_unit_column_test:differential_privacy_approx_quantiles_int64_explicit_bounds_multi_user_with_report_json_zero_rows"
  label: "differential_privacy_unit_column_test:differential_privacy_approx_quantiles_int64_explicit_bounds_multi_user_with_report_proto"
  label: "differential_privacy_unit_column_test:differential_privacy_approx_quantiles_int64_explicit_bounds_multi_user_with_report_proto_zero_rows"
  label: "differential_privacy_unit_column_test:differential_privacy_avg_double_explicit_bounds"
  label: "differential_privacy_unit_column_test:differential_privacy_avg_double_explicit_bounds_multi_user"
  label: "differential_privacy_unit_column_test:differential_privacy_avg_double_explicit_bounds_multi_user_with_report_json"
  label: "differential_privacy_unit_column_test:differential_privacy_avg_double_explicit_bounds_multi_user_with_report_json_zero_rows"
  label: "differential_privacy_unit_column_test:differential_privacy_avg_double_explicit_bounds_multi_user_with_report_proto"
  label: "differential_privacy_unit_column_test:differential_privacy_avg_double_explicit_bounds_multi_user_with_report_proto_zero_rows"
  label: "differential_privacy_unit_column_test:differential_privacy_avg_int64_explicit_bounds"
  label: "differential_privacy_unit_column_test:differential_privacy_avg_int64_explicit_bounds_multi_user"
  label: "differential_privacy_unit_column_test:differential_privacy_avg_int64_explicit_bounds_multi_user_smaller_delta"
  label: "differential_privacy_unit_column_test:differential_privacy_avg_int64_implicit_bounds_multi_user_with_report_json"
  label: "differential_privacy_unit_column_test:differential_privacy_avg_int64_implicit_bounds_multi_user_with_report_json_zero_rows"
  label: "differential_privacy_unit_column_test:differential_privacy_avg_int64_implicit_bounds_multi_user_with_report_proto"
  label: "differential_privacy_unit_column_test:differential_privacy_avg_int64_implicit_bounds_multi_user_with_report_proto_zero_rows"
  label: "differential_privacy_unit_column_test:differential_privacy_basic_approx_quantiles_explicit_bounds"
  label: "differential_privacy_unit_column_test:differential_privacy_basic_approx_quantiles_explicit_bounds_result_length"
  label: "differential_privacy_unit_column_test:differential_privacy_basic_avg_double_implicit_bounds"
  label: "differential_privacy_unit_column_test:differential_privacy_basic_avg_double_implicit_bounds_multi_user"
  label: "differential_privacy_unit_column_test:differential_privacy_basic_avg_int64_implicit_bounds"
  label: "differential_privacy_unit_column_test:differential_privacy_basic_count_int64_implicit_bounds_multi_user_with_report_json"
  label: "differential_privacy_unit_column_test:differential_privacy_basic_count_int64_implicit_bounds_multi_user_with_report_json_zero_rows"
  label: "differential_privacy_unit_column_test:differential_privacy_basic_count_int64_implicit_bounds_multi_user_with_report_proto"
  label: "differential_privacy_unit_column_test:differential_privacy_basic_count_int64_implicit_bounds_multi_user_with_report_proto_zero_rows"
  label: "differential_privacy_unit_column_test:differential_privacy_basic_delta_not_set"
  label: "differential_privacy_unit_column_test:differential_privacy_basic_delta_too_large"
  label: "differential_privacy_unit_column_test:differential_privacy_basic_epsilon_not_set"
  label: "differential_privacy_unit_column_test:differential_privacy_basic_percentile_cont_explicit_bounds"
  label: "differential_privacy_unit_column_test:differential_privacy_basic_percentile_cont_implicit_bounds"
  label: "differential_privacy_unit_column_test:differential_privacy_basic_percentile_cont_implicit_bounds_with_params"
  label: "differential_privacy_unit_column_test:differential_privacy_basic_stddev_pop_explicit_bounds"
  label: "differential_privacy_unit_column_test:differential_privacy_basic_stddev_pop_explicit_bounds_all_nulls"
  label: "differential_privacy_unit_column_test:differential_privacy_basic_stddev_pop_implicit_bounds"
  label: "differential_privacy_unit_column_test:differential_privacy_basic_sum_double_implicit_bounds"
  label: "differential_privacy_unit_column_test:differential_privacy_basic_sum_double_implicit_bounds_multi_user"
  label: "differential_privacy_unit_column_test:differential_privacy_basic_sum_int64_implicit_bounds"
  label: "differential_privacy_unit_column_test:differential_privacy_basic_sum_int64_implicit_bounds_multi_user"
  label: "differential_privacy_unit_column_test:differential_privacy_basic_sum_int64_implicit_bounds_multi_user_with_report_json"
  label: "differential_privacy_unit_column_test:differential_privacy_basic_sum_int64_implicit_bounds_multi_user_with_report_json_zero_rows"
  label: "differential_privacy_unit_column_test:differential_privacy_basic_sum_int64_implicit_bounds_multi_user_with_report_proto"
  label: "differential_privacy_unit_column_test:differential_privacy_basic_sum_int64_implicit_bounds_multi_user_with_report_proto_zero_rows"
  label: "differential_privacy_unit_column_test:differential_privacy_basic_var_pop_explicit_bounds"
  label: "differential_privacy_unit_column_test:differential_privacy_basic_var_pop_explicit_bounds_all_nulls"
  label: "differential_privacy_unit_column_test:differential_privacy_basic_var_pop_implicit_bounds"
  label: "differential_privacy_unit_column_test:differential_privacy_count_double_explicit_bounds_multi_user_with_report_json"
  label: "differential_privacy_unit_column_test:differential_privacy_count_double_explicit_bounds_multi_user_with_report_json_zero_rows"
  label: "differential_privacy_unit_column_test:differential_privacy_count_double_explicit_bounds_multi_user_with_report_proto"
  label: "differential_privacy_unit_column_test:differential_privacy_count_double_explicit_bounds_multi_user_with_report_proto_zero_rows"
  label: "differential_privacy_unit_column_test:differential_privacy_count_star_explicit_bounds_multi_user_with_report_json"
  label: "differential_privacy_unit_column_test:differential_privacy_count_star_explicit_bounds_multi_user_with_report_proto"
  label: "differential_privacy_unit_column_test:differential_privacy_count_unique_users_with_report_json_thresholding"
  label: "differential_privacy_unit_column_test:differential_privacy_delta_eliminates_row"
  label: "differential_privacy_unit_column_test:differential_privacy_delta_eliminates_row_for_avg"
  label: "differential_privacy_unit_column_test:differential_privacy_explicit_bounds_avg_and_count"
  label: "differential_privacy_unit_column_test:differential_privacy_explicit_bounds_sum_and_count"
  label: "differential_privacy_unit_column_test:differential_privacy_max_groups_contributed_group_by_1"
  label: "differential_privacy_unit_column_test:differential_privacy_max_groups_contributed_group_by_2"
  label: "differential_privacy_unit_column_test:differential_privacy_max_groups_contributed_group_by_3"
  label: "differential_privacy_unit_column_test:differential_privacy_max_groups_contributed_scalar_aggregation"
  label: "differential_privacy_unit_column_test:differential_privacy_max_groups_contributed_scalar_aggregation_explicit"
  label: "differential_privacy_unit_column_test:differential_privacy_public_groups_with_privacy_unit_column_and_group_by_and_max_groups_contributed"
  label: "differential_privacy_unit_column_test:differential_privacy_sum_double_explicit_bounds"
  label: "differential_privacy_unit_column_test:differential_privacy_sum_double_explicit_bounds_multi_user"
  label: "differential_privacy_unit_column_test:differential_privacy_sum_double_explicit_bounds_multi_user_with_report_json"
  label: "differential_privacy_unit_column_test:differential_privacy_sum_double_explicit_bounds_multi_user_with_report_json_zero_rows"
  label: "differential_privacy_unit_column_test:differential_privacy_sum_double_explicit_bounds_multi_user_with_report_proto"
  label: "differential_privacy_unit_column_test:differential_privacy_sum_double_explicit_bounds_multi_user_with_report_proto_zero_rows"
  label: "differential_privacy_unit_column_test:differential_privacy_sum_int64_explicit_bounds"
  label: "differential_privacy_unit_column_test:differential_privacy_sum_int64_explicit_bounds_multi_user"
  label: "differential_privacy_unit_column_test:differential_privacy_sum_int64_explicit_bounds_multi_user_smaller_delta"
  label: "differential_privacy_unit_column_test:differential_privacy_verify_non_randomness_of_approx_quantiles_explicit_bounds"
  label: "differential_privacy_unit_column_test:differential_privacy_verify_non_randomness_of_approx_quantiles_explicit_bounds_2"
  label: "differential_privacy_unit_column_test:differential_privacy_verify_non_randomness_of_percentile_cont_implicit_bounds"
  label: "differential_privacy_unit_column_test:differential_privacy_verify_non_randomness_of_percentile_cont_implicit_bounds_2"
  label: "differential_privacy_unit_column_test:differential_privacy_verify_non_randomness_of_var_pop_implicit_bounds"
  label: "differential_privacy_unit_column_test:differential_privacy_verify_randomness_of_var_pop_implicit_bounds"
}
known_errors {
  mode: ALLOW_ERROR
  reason: "RET_CHECK failure (zetasql/analyzer/rewriters/insert_dml_values_rewriter.cc:61) column->HasDefaultExpression() No default expression exists for the column specified with DEFAULT keyword in insert dml"
  label: "dml_insert_test:insert_default"
}
known_errors {
  mode: ALLOW_UNIMPLEMENTED
  reason: "Example: WITH GROUP_ROWS subqueries are not supported in ORDER_BY_AND_LIMIT_IN_AGGREGATE rewriter"
  label: "with_group_rows_test:aggregate_extra_inner_key"
  label: "with_group_rows_test:aggregate_key1"
  label: "with_group_rows_test:aggregate_key2"
  label: "with_group_rows_test:aggregate_two_inner_keys"
  label: "with_group_rows_test:distinct_column_values"
  label: "with_group_rows_test:outer_agg_with_limit"
}

known_errors {
  mode: ALLOW_UNIMPLEMENTED
  reason: "Multi-level aggregation is not yet supported in the ORDER_BY_AND_LIMIT_IN_AGGREGATE rewriter"
  label: "multi_level_aggregation_basic_test:multi_level_emps_metrics_by_dept"
  label: "multi_level_aggregation_complex_test:multi_level_agg_with_order_by_modifier"
  label: "multi_level_aggregation_complex_test:multi_level_agg_with_order_by_and_limit_1"
  label: "multi_level_aggregation_complex_test:multi_level_agg_with_order_by_and_limit_2"
  label: "multi_level_aggregation_complex_test:multi_level_agg_many_clauses"
  label: "multi_level_aggregation_basic_test:multi_level_emps_metrics_by_dept_ignore_nulls"
  label: "multi_level_aggregation_complex_test:multi_level_agg_with_order_by_modifier_ignore_nulls"
  label: "multi_level_aggregation_complex_test:multi_level_agg_with_order_by_and_limit_1_ignore_nulls"
  label: "multi_level_aggregation_complex_test:multi_level_agg_with_order_by_and_limit_2_ignore_nulls"
  label: "multi_level_aggregation_complex_test:multi_level_agg_many_clauses_ignore_nulls"
  label: "multi_level_aggregation_complex_test:multi_level_agg_many_clauses_nullable_ignore_nulls"
}

known_errors {
  mode: ALLOW_UNIMPLEMENTED
  reason: "GROUP BY modifiers are not supported in ORDER_BY_AND_LIMIT_IN_AGGREGATE rewriter"
  label: "call_sql_udas_with_multi_level_agg_test:call_array_agg_sum_with_non_aggregate_args"
  label: "call_sql_udas_with_multi_level_agg_test:call_udf_calling_udas"
  label: "call_sql_tvfs_with_multi_level_agg_test:call_multiple_aggs_with_ordering_tvf"
  label: "call_sql_tvfs_with_multi_level_agg_test:call_templated_multiple_aggs_with_ordering_tvf"
  label: "multi_level_aggregation_complex_test:multi_level_agg_many_clauses"
  label: "multi_level_aggregation_complex_test:multi_level_agg_with_order_by_and_limit_1"
  label: "multi_level_aggregation_complex_test:multi_level_agg_with_order_by_and_limit_2"
  label: "multi_level_aggregation_complex_test:multi_level_agg_with_order_by_modifier"
  label: "multi_level_aggregation_basic_test:multi_level_emps_metrics_by_dept"
  label: "multi_level_aggregation_basic_test:multi_level_emps_metrics_by_dept_ignore_nulls"
  label: "multi_level_aggregation_complex_test:multi_level_agg_with_order_by_modifier_ignore_nulls"
  label: "multi_level_aggregation_complex_test:multi_level_agg_with_order_by_and_limit_1_ignore_nulls"
  label: "multi_level_aggregation_complex_test:multi_level_agg_with_order_by_and_limit_2_ignore_nulls"
  label: "multi_level_aggregation_complex_test:multi_level_agg_many_clauses_ignore_nulls"
  label: "multi_level_aggregation_complex_test:multi_level_agg_many_clauses_nullable_ignore_nulls"
}

known_errors {
  mode: ALLOW_UNIMPLEMENTED
  reason: "The function inliner does not yet support TVFs with correlated argument references"
  label: "lateral_join_on_tvf_test:lateral_join_with_tvf"
  label: "lateral_join_on_tvf_test:lateral_left_join_with_tvf"
}

known_errors {
  mode: ALLOW_UNIMPLEMENTED
  reason: "WITH clauses under subquery in DML statement is not supported yet"
  label: "graph_table_gql_extended_test:delete_dml_exists_graph_subquery_set_op_after_next"
}

known_errors {
  mode: ALLOW_UNIMPLEMENTED
  reason: "SIMPLE path mode not supported"
  label: "graph_table_gql_extended_test:path_is_simple_quantified_with_path_mode"
  label: "graph_table_gql_extended_test:path_is_simple_with_path_mode"
  label: "graph_table_gql_extended_test:simple_path_mode_with_array_edges"
  label: "graph_table_gql_extended_test:simple_path_mode_with_array_edges_and_duplicate_scalar_nodes"
  label: "graph_table_gql_extended_test:simple_path_mode_with_array_edges_of_different_types"
  label: "graph_table_gql_extended_test:simple_path_mode_with_array_edges_over_quantified_paths"
  label: "graph_table_gql_extended_test:simple_path_mode_with_duplicate_scalar_nodes"
  label: "graph_table_gql_extended_test:simple_path_mode_with_scalar_and_array_edges"
  label: "graph_table_gql_extended_test:simple_path_mode_with_scalar_and_array_edges_of_different_types"
  label: "graph_table_gql_extended_test:simple_path_mode_with_scalar_and_long_array_edges_of_different_types"
  label: "graph_table_gql_extended_test:simple_path_mode_with_scalar_edges"
  label: "graph_table_gql_extended_test:simple_path_mode_with_scalar_edges_of_different_types"
  label: "graph_table_gql_extended_test:simple_path_mode_with_scalar_edges_within_quantified_paths"
}

known_errors {
  mode: ALLOW_ERROR_OR_WRONG_ANSWER
  reason: "MATCH ANY with ties is nondeterministic"
  label: "graph_table_gql_extended_test:any_with_ties_counting_hops"
  label: "graph_table_gql_extended_test:shortest_with_ties"
}

known_errors {
  mode: ALLOW_UNIMPLEMENTED
  reason: "Measure type rewriter does not support scalar subqueries that emit measure columns"
  label: "measures_test:aggregate_measure_from_scalar_subquery"
  label: "measures_test:aggregate_measure_from_scalar_subquery_in_with_query"
  label: "measures_test:measure_exprs_with_clauses_non_deterministic"
  label: "measures_test:measure_from_with_expr_assignment_list_as_scalar_subquery"
  label: "measures_test:measure_from_with_expr_from_scalar_subquery"
}

known_errors {
  mode: ALLOW_UNIMPLEMENTED
  reason: "Aggregate functions with GROUP BY modifiers are not supported in ORDER_BY_AND_LIMIT_IN_AGGREGATE rewriter"
  label: "measures_test:measure_exprs_with_clauses_non_deterministic"
}

known_errors {
  mode: ALLOW_UNIMPLEMENTED
  reason: "Measure type rewriter does not support WITH expressions emitting a measure type"
  label: "measures_test:measure_from_with_expr_assignment_list_as_column_ref"
  label: "measures_test:measure_from_with_expr_from_column_ref"
}

known_errors {
  mode: ALLOW_UNIMPLEMENTED
  reason: "Measure type rewriter expects argument to AGG function to be a direct column reference"
  label: "measures_test:null_measure_value_from_limit_zero"
  label: "measures_test:null_measure_value_from_where_false"
}

# TODO: b/439843654 - Remove this once MULTILEVEL_AGGREGATION_ON_UDAS is
# removed from development. Currently, the reference driver with all rewrites
# does not respect prepare_database_additional_features.
known_errors {
  mode: ALLOW_ERROR
  reason: "Reference driver with all rewrites does not support GROUP BY modifiers"
  label: "call_sql_udas_with_multi_level_agg_test:call_count_times_two_over_max_by_key"
  label: "call_sql_udas_with_multi_level_agg_test:call_max_times_two_over_max_by_key"
  label: "call_sql_udas_with_multi_level_agg_test:call_sum_squares_over_sum_times_two_by_key"
  label: "call_sql_udas_with_multi_level_agg_test:call_sum_times_two_over_max_by_key"
}
