#
# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Known errors file for zetasql compliance framework. Add labels and queries
# here to exclude them from compliance tests.

known_errors {
  mode: ALLOW_ERROR
  reason: "Casts not yet implemented"
  label: "code:CastTo_DATE_UINT(32|64)_NULL"
  label: "code:CastTo_INT32_TIMESTAMP_.*_NULL"
  label: "code:CastTo_TIMESTAMP_.*_U?INT(32|64)_NULL"
  label: "code:CastTo_TIMESTAMP_.*_STRING_.*"
  label: "code:CastTo_UINT(32|64)_DATE_NULL"
  label: "code:CastTo_UINT(32|64)_TIMESTAMP_.*_NULL"
  label: "code:CastTo_STRING_TIMESTAMP_MICROS_1391258096123456"
  label: "code:CastTo_STRING_TIMESTAMP_MILLIS_1391258096123"
  label: "code:CastTo_STRING_TIMESTAMP_NANOS_1391258096123456789"
  label: "code:CastTo_STRING_TIMESTAMP_SECONDS_1391258096"
}

known_errors {
  mode: ALLOW_ERROR
  reason: "These aggregate functions are not implemented in the reference implementation yet"
  label: "analytic_st_accum.test:analytic_st_accum_basic"
  label: "analytic_kll_quantiles.test:analytic_kll_quantiles_init_int64_basic"
  label: "analytic_kll_quantiles.test:analytic_kll_quantiles_init_uint64_basic"
  label: "analytic_kll_quantiles.test:analytic_kll_quantiles_init_double_basic"
  label: "analytic_kll_quantiles.test:analytic_kll_quantiles_merge_partial_basic"
  label: "analytic_kll_quantiles.test:analytic_kll_quantiles_merge_int64_basic"
  label: "analytic_kll_quantiles.test:analytic_kll_quantiles_merge_uint64_basic"
  label: "analytic_kll_quantiles.test:analytic_kll_quantiles_merge_double_basic"
  label: "analytic_kll_quantiles.test:analytic_kll_quantiles_merge_point_int64_basic"
  label: "analytic_kll_quantiles.test:analytic_kll_quantiles_merge_point_uint64_basic"
  label: "analytic_kll_quantiles.test:analytic_kll_quantiles_merge_point_double_basic"
}

known_errors {
  mode: ALLOW_ERROR
  reason: "These functions are not implemented in the reference implementation yet"
  label: "collation_test:string_agg_with_sort_key_with_collation_.*"
  label: "collation_test:analytic_function_.*_with_collation_.*"
}
